# Generated by Django 2.2.4 on 2021-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexamen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plan',
            field=models.TextField(),
        ),
    ]
